server:
  port: 10000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:hs-notification
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_sql_comments: true

    defer-datasource-initialization: true
    show-sql: true
